### ISSUE TITLE
no idea how to use

### ISSUE THREAD

**Issue by leuchtrakete666** [matheusmoreira/ite-829x#2]
i have exactly this keyboard and nowhere to find a proper tool to manage rgb in linux for it. please give some assistance how to use your tool.

thanks

**Comment by matheusmoreira** [comment]
Yeah, it's probably not very easy to use... In order to save time I made a simple command interface and left most of the documentation in the source code. In any case, I'll describe how it currently works.

When you run `ite-829x`, it will read commands from standard input, one per line. Each command instructs the tool to configure the keyboard LEDs in some way. Usually the input is connected to your terminal so you can start typing commands right away and press `Ctrl+D` when you are done. Alternatively, you can write the commands to a file and use that as input:

    ite-829x < keyboard.cfg

Here are the important commands:

 - `reset`
   Turns off all LEDs and clears all key color configuration.
 - `brightness N`
   Sets LED brightness.
   N is a number from 0 to 10.
   0 means the LEDs are turned off.
 - `led N R G B`
   Sets LED number N to the specified R G B color.
   N is a number from 0 to 179 representing each LED in the keyboard ordered left to right, from the top down.
   Some keys have multiple LEDs.
   A more detailed list is in the source code.
 - `effects N`
   Enables keyboard effects.
   N is a number from 0 to 6 denoting effects like wave, breathe, scan, etc.

When the laptop boots it sets the keyboard LEDs to an extremely bright blue color. So after logging in I turn it off using the following commands:

```
reset
brightness 0
```

With the `led` command you can create any sort of color scheme you can think of. For example:

```
led 0   255 0   0
led 165 0   255 0
led 169 0   0   255
```

Sets the `Esc` key LED to red.
Sets the space bar's leftmost LED to green.
Sets the space bar's rightmost LED to blue.

Every time you `reset` the keyboard, you must send all the `led` commands for all the keys to the keyboard again. So write them to a file! That way you can even have specific profiles for different applications.

**Comment by leuchtrakete666** [comment]
thanks a lot. i will try.
